on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
  build_manylinux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
    - name: Setup vcpkg (it does not install any package yet)
      uses: lukka/run-vcpkg@v11
