on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup vcpkg (it does not install any package yet)
        uses: lukka/run-vcpkg@v11
  build_manylinux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup vcpkg (it does not install any package yet)
        uses: lukka/run-vcpkg@v11
